name = "tullamore"
compatibility_date = "2025-01-01"
compatibility_flags = ["nodejs_compat"]

main = "worker.ts"
assets = { directory = ".svelte-kit/cloudflare/", binding = "ASSETS" }

[[d1_databases]]
binding = "DB"
database_name = "tullamore"
database_id = "c0c65eba-4eaa-464c-9294-40e25e63d5dc"
migrations_dir = "drizzle"

[[kv_namespaces]]
binding = "KV"
id = "fabfbf60a3a444a89992788d512910a7"

[[r2_buckets]]
binding = "R2"
bucket_name = "tullamore"

[vars]
MOCK_AI = "false"
